src/rpcmining.cpp
Some JSON libraries cannot parse integers greater than 2^53-1.
So clamp "no limit" 2^64 sigop/sighash limits to 2^53-1 before
returning them.
A couple of implementation notes:
Changing the constant returned by the consensus/params.h methods
from uint64_t::max to 2^53-1 would be another fix, but that felt
like a layering violation: the consensus code shouldn't care about
details of representing numbers in JSON.
Also, I didn't define JSON_NUMBER_LIMIT in a .h file because it
isn't clear where it belongs (util.h? one of the json/ .h?) and
because at this point it makes sense to try to create patches
that change fewer files.
Fixes issue# 45.
After review, should be pulled into the only_bigblocks branch, also.
=> Avoid exceeding maximum safe Javascript integer

src/init.cpp
Add help output for stealth-mode and limitrespendrelay parameters.
=> adding documentation for config params

src/main.h
Cherry-pick of https://github.com/bitcoinclassic/bitcoinclassic/pull/140
=> Increase min diskspace

src/Makefile.test.include, src/init.cpp, src/main.cpp, src/main.h, src/options.cpp, src/options.h, src/qt/optionsdialog.cpp, src/qt/optionsmodel.cpp, src/test/clientversion_tests.cpp, src/test/options_tests.cpp, src/test/test_bitcoin.cpp
This is a cherry-pick of https://github.com/bitcoinclassic/bitcoinclassic/pull/143
=> Extend checkpointing to a safe distance in the past

contrib/gitian-debian/build.sh
Allows for other methods of synchronization besides ntp. Issue #131.
=> Move ntp from Depends to Recommends.

qa/rpc-tests/pruning.py, qa/rpc-tests/test_framework/util.py
=> Fix pruning test timeouts

src/rpcblockchain.cpp
Cherry pick of https://github.com/bitcoin/bitcoin/pull/7827
=> Speed up getchaintips.

src/init.cpp, src/txdb.h
Cherry picks of https://github.com/bitcoin/bitcoin/pull/8273 amd https://github.com/bitcoin/bitcoin/pull/8407
=> Bump default dbcache

qa/rpc-tests/reindex.py, src/init.cpp, src/main.cpp, src/main.h
https://github.com/bitcoin/bitcoin/pull/7917
=> Optimize reindex

src/main.cpp
=> DRY: Exception handling for thin blocks.

src/qt/guiutil.cpp
This fixes a small bug causing the qt application to sometimes disappear on multi monitor system.
Versions of this have been accepted by unlimited, classic & core. This is the classic version (and the best IMHO). 
See the following PR's for details:
https://github.com/bitcoinclassic/bitcoinclassic/pull/258
https://github.com/bitcoinclassic/bitcoinclassic/pull/257
https://github.com/bitcoin/bitcoin/pull/10156
https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/419
=> Multiple monitor bugfix

src/chain.h
https://github.com/bitcoin/bitcoin/pull/7964
=> chain: define enum used as bit field as uint32_t

src/main.cpp, src/net.cpp
Cherry-pick of https://github.com/bitcoin/bitcoin/pull/8594 and https://github.com/bitcoin/bitcoin/pull/8740.
=> Do not add random inbound peers to addrman.

src/main.cpp, src/net.cpp, src/net.h
Cherry-pick of https://github.com/bitcoin/bitcoin/pull/7856.
=> Only send one GetAddr response per connection.

src/qt/paymentrequestplus.cpp
https://github.com/bitcoin/bitcoin/pull/9326 Fix qt/paymentrequestplus.cpp for OpenSSL 1.1 API
=> Fix qt/paymentrequestplus.cpp for OpenSSL 1.1 API

qa/rpc-tests/txn_clone.py
Cherry-pick of https://github.com/bitcoin/bitcoin/pull/6414
Alternative to #210
=> Fix intermittent test failure, reduce test time

depends/packages/miniupnpc.mk
https://github.com/bitcoin/bitcoin/pull/10414
=> [depends] miniupnpc 2.0.20170509

src/main.cpp
Fixes test regression in https://github.com/bitcoinxt/bitcoinxt/pull/212
=> Add missing arguments to log statement

src/Makefile.am, src/Makefile.test.include, src/main.cpp, src/test/utilfork_tests.cpp, src/utilfork.cpp, src/utilfork.h
Regtests fork at genesis, so the check in ConnectTip needs to support this.
=> UAHF: Move check for fork activation to a function 

qa/pull-tester/rpc-tests.py, qa/rpc-tests/bip65-cltv-p2p.py, qa/rpc-tests/bip68-112-113-p2p.py, qa/rpc-tests/bip9-softforks.py, qa/rpc-tests/bipdersig-p2p.py, qa/rpc-tests/decodescript.py, qa/rpc-tests/keypool.py, qa/rpc-tests/listtransactions.py, qa/rpc-tests/p2p-acceptblock.py, qa/rpc-tests/p2p-fullblocktest.py, qa/rpc-tests/pruning.py, qa/rpc-tests/rawtransactions.py, qa/rpc-tests/rest.py, qa/rpc-tests/smartfees.py, qa/rpc-tests/test_framework/blockstore.py, qa/rpc-tests/test_framework/blocktools.py, qa/rpc-tests/test_framework/comptool.py, qa/rpc-tests/test_framework/mininode.py, qa/rpc-tests/test_framework/netutil.py, qa/rpc-tests/test_framework/socks5.py, qa/rpc-tests/test_framework/test_framework.py, qa/rpc-tests/wallet.py, src/main.cpp
Cherry-picks of https://github.com/bitcoin/bitcoin/pull/7778. That PR touches a lot of files and code, including some tests we don't have and some that are not interesting (like RBF etc.). We also already had some of these changes. I've attempted to pull over everything relevant.
=> Use python2/3 syntax

qa/pull-tester/rpc-tests.py, qa/rpc-tests/abc-p2p-fullblocktest.py, qa/rpc-tests/mempool-accept-txn.py, qa/rpc-tests/test_framework/cdefs.py, qa/rpc-tests/test_framework/key.py, qa/rpc-tests/test_framework/mininode.py, src/main.cpp
=> [qa] UAHF tests

src/leveldbwrapper.cpp
https://github.com/bitcoin/bitcoin/pull/6551
=> Handle leveldb::DestroyDB() errors on wipe failure

src/tinyformat.h
https://github.com/bitcoin/bitcoin/pull/11573
Removes compilation warnings.
=> [Util] Update tinyformat.h

src/leveldbwrapper.cpp, src/leveldbwrapper.h, src/txdb.cpp
Commit from https://github.com/bitcoin/bitcoin/pull/6777, but with db obfuscation removed.
=> Encapsulate CLevelDB iterators

src/dbwrapper.cpp, src/dbwrapper.h
https://github.com/bitcoin/bitcoin/pull/7927, except for obfuscation key stuff, which we don't implement.
Build on top of https://github.com/bitcoinxt/bitcoinxt/pull/274
=> Minor changes to dbwrapper 

src/dbwrapper.cpp, src/init.cpp
https://github.com/bitcoin/bitcoin/pull/9999
Build on top of #282
=> [LevelDB] Plug leveldb logs to bitcoin logs

src/test/coins_tests.cpp
Tests from PR https://github.com/bitcoin/bitcoin/pull/6932 (commits 03c8282 and 1cf3dd8).
=> Add test for UpdateCoins

src/coins.cpp, src/test/coins_tests.cpp
https://github.com/bitcoin/bitcoin/pull/5967
Build on top of #285
=> Alter assumptions in CCoinsViewCache::BatchWrite

qa/rpc-tests/smartfees.py
Includes https://github.com/bitcoin/bitcoin/pull/7980
=> Fixes to smartfees.py

configure.ac, src/Makefile.am, src/Makefile.bench.include, src/bench/Examples.cpp, src/bench/MilliSleep.cpp, src/bench/bench.cpp, src/bench/bench.h, src/bench/bench_bitcoin.cpp
https://github.com/bitcoin/bitcoin/pull/6733
=> Simple benchmarking framework

src/base58.cpp, src/base58.h, src/test/bip32_tests.cpp
https://github.com/bitcoin/bitcoin/pull/6468 - fix CBitcoinExtKeyBase template
https://github.com/bitcoin/bitcoin/pull/7656 - Improve EncodeBase58
https://github.com/bitcoin/bitcoin/pull/8736 - base58: Improve DecodeBase58 performance
https://github.com/bitcoin/bitcoin/pull/10961 - Improve readability of DecodeBase58Check(...)
=> Base58 cherries

qa/rpc-tests/wallet.py
https://github.com/bitcoin/bitcoin/pull/7229
We already had the fix. This adds the tests.
=> [qa] wallet: Check if maintenance changes the balance

qa/rpc-tests/walletbackup.py
https://github.com/bitcoin/bitcoin/pull/8724
=> [qa] walletbackup: Sync blocks inside the loop

qa/rpc-tests/signrawtransactions.py, src/core_read.cpp, src/rpcrawtransaction.cpp
https://github.com/bitcoin/bitcoin/pull/9650
=> Better handle invalid parameters to signrawtransaction

qa/pull-tester/rpc-tests.py, qa/rpc-tests/disablewallet.py, src/rpcmisc.cpp
* Return all available information via RPC call "validateaddress - https://github.com/bitcoin/bitcoin/pull/6262
* Fix crash in validateaddress with -disablewallet - https://github.com/bitcoin/bitcoin/pull/6970
=> Return all available information via RPC call "validateaddress"

src/Makefile.am, src/init.cpp, src/rpcserver.cpp, src/rpcserver.h, src/test/test_bitcoin.cpp, src/wallet/rpcwallet.cpp, src/wallet/rpcwallet.h, src/wallet/wallet.h
https://github.com/bitcoin/bitcoin/pull/7307
=> [RPC, Wallet] Move RPC dispatch table registration to wallet/ code

src/net.cpp, src/net.h
https://github.com/bitcoin/bitcoin/pull/9698
=> net: fix socket close race

src/addrman.cpp, src/addrman.h, src/main.cpp, src/net.cpp, src/net.h, src/netbase.cpp, src/random.cpp, src/random.h, src/test/addrman_tests.cpp, src/test/coins_tests.cpp, src/test/crypto_tests.cpp, src/test/net_tests.cpp, src/test/pmt_tests.cpp, src/test/scheduler_tests.cpp, src/test/sighash_tests.cpp, src/test/skiplist_tests.cpp, src/test/test_bitcoin.cpp, src/test/test_random.h, src/test/util_tests.cpp, src/test/versionbits_tests.cpp, src/test/xthin_tests.cpp, src/txmempool.cpp, src/wallet/wallet.cpp, src/xthin.cpp
https://github.com/bitcoin/bitcoin/pull/8914
FastRandomContext is used by cashaddr tests
=> Kill insecure_random and associated global state

qa/rpc-tests/test_framework/authproxy.py, qa/rpc-tests/wallet.py
Depends on #317
Commits a406fcb and 6bbb4ef from https://github.com/bitcoin/bitcoin/pull/7892, the other changes are part of #317
=> Add full UTF-8 support to RPC

src/main.cpp
Thanks to #293 it is finally possible to stop hijacking the final `return true` in ATMP.
The diff looks less scary with `git show --diff-algorithm=histogram`.
=> Improve readability in ATMP

src/net.cpp, src/netbase.cpp
https://github.com/bitcoin/bitcoin/pull/12326
=> net: initialize socket to avoid closing random fd's

qa/rpc-tests/bip100-sizelimit.py
=> [qa] Remove sync_blocks from bip100-sizelimit

qa/rpc-tests/blockchain.py, src/rpc/blockchain.cpp
https://github.com/bitcoin/bitcoin/pull/7774
=> RPC: add versionHex in getblock and getblockheader JSON results

src/respend/respendaction.h, src/respend/respenddetector.cpp, src/respend/respenddetector.h, src/respend/respendlogger.cpp, src/respend/respendlogger.h, src/respend/respendrelayer.cpp, src/respend/respendrelayer.h, src/respend/test/respenddetector_tests.cpp, src/respend/test/respendrelayer_tests.cpp, src/respend/test/walletnotifier_tests.cpp, src/respend/walletnotifier.cpp, src/respend/walletnotifier.h
Enables respend actions to make use of pool entry time and various calculated quantities.
=> Make mempool entry available to respend actions

src/Makefile.am, src/init.cpp, src/rest.cpp, src/rpc/blockchain.cpp, src/rpc/mining.cpp, src/rpc/misc.cpp, src/rpc/net.cpp, src/rpc/rawtransaction.cpp, src/rpc/register.h, src/rpc/server.cpp, src/rpc/server.h, src/test/rpc_tests.cpp, src/test/test_bitcoin.cpp, src/wallet/rpcwallet.cpp, src/wallet/rpcwallet.h, src/wallet/test/wallet_test_fixture.cpp
https://github.com/bitcoin/bitcoin/pull/7766
Depends on #329
=> rpc: Register calls where they are defined

src/httprpc.cpp, src/qt/rpcconsole.cpp, src/rpc/server.cpp, src/rpc/server.h
https://github.com/bitcoin/bitcoin/pull/7317
=> Fix RPCTimerInterface ordering issue

qa/rpc-tests/pruning.py, qa/rpc-tests/test_framework/util.py
https://github.com/bitcoin/bitcoin/pull/9274
=> [qa] Use cached utxo set to fix performance regression

src/blockheaderprocessor.cpp, src/blockprocessor.cpp, src/blockprocessor.h, src/main.cpp, src/main.h, src/test/DoS_tests.cpp, src/thinblockconcluder.cpp
=> Add misbehave reason to Misbehave

qa/rpc-tests/blockchain.py, src/rpc/mining.cpp
https://github.com/bitcoin/bitcoin/pull/10229 - Tests: Add test for getdifficulty                     
https://github.com/bitcoin/bitcoin/pull/7480 - Changed getnetworkhps value to double to avoid overflow.
https://github.com/bitcoin/bitcoin/pull/10253 - [test] Add test for getnetworkhashps
=> blockchain.py cherries

src/init.cpp, src/main.cpp
Don't silently ignore the blocks.
=> Log ignored blocks in AcceptBlock

src/compressor.h, src/script/interpreter.cpp, src/script/script.h, src/streams.h, src/test/coins_tests.cpp
https://github.com/bitcoin/bitcoin/pull/7933
=> Fix OOM when deserializing UTXO entries with invalid length

src/main.cpp
https://github.com/bitcoin/bitcoin/pull/10297
=> Simplify DisconnectBlock arguments/return value

src/dbwrapper.h, src/streams.h, src/wallet/db.cpp, src/wallet/db.h
https://github.com/bitcoin/bitcoin/pull/9353
=> Add data() method to CDataStream (and use it) 

src/policy/policy.cpp, src/script/script.cpp, src/script/script.h, src/script/standard.cpp, src/script/standard.h, src/test/transaction_tests.cpp
https://github.com/bitcoin/bitcoin/pull/6424
On top of #358
=> Policy: Decouple Solver() from nMaxDatacarrierBytes (for free)

src/script/standard.h, src/test/transaction_tests.cpp
https://github.com/Bitcoin-ABC/bitcoin-abc/pull/41
Build on top of #359
=> Update default datacarriersize to 220 bytes

qa/rpc-tests/test_framework/mininode.py, qa/rpc-tests/test_framework/util.py, src/init.cpp
https://github.com/bitcoin/bitcoin/pull/10123 - Allow debug logs to be excluded from specified component
https://github.com/bitcoin/bitcoin/pull/10124 - [test] Suppress test logging spam
On top of #353
=> Reduce noise in QA logs

src/blocksender.cpp, src/chain.h, src/main.cpp, src/thinblockmanager.cpp
I have not been able to reproduce the pruning.py failures we're having after applying this fix.
Also adds some logging that helped me find the problem.
=> Add missing lock in getblocktxn

src/init.cpp, src/main.cpp, src/script/sigcache.cpp, src/script/sigcache.h
https://github.com/bitcoin/bitcoin/pull/6918
=> Make sigcache faster, more efficient, larger

src/script/script.cpp, src/script/script.h, src/test/scriptnum_tests.cpp
* Pull minimal check out of CScriptNum constr. into IsMinimalArray - https://reviews.bitcoinabc.org/D1214
* Ensure that CScriptNum is self contained (SQUASHED) - https://reviews.bitcoinabc.org/D1218
* Add function to trim leading array zeros maintaining MSB. - https://reviews.bitcoinabc.org/D1215
* Refactor MinimalizeBigEndianArray t be part of CScriptNum (SQUASHED) https://reviews.bitcoinabc.org/D1219
=> Add IsMinimallyEncoded and MinimallyEncode to CScriptNum

qa/rpc-tests/test_framework/util.py, src/blockprocessor.cpp, src/main.cpp
A couple of unrelated improvements to error messages
This is used in #375
=> Error message improvements

src/Makefile.test.include, src/chain.cpp, src/chain.h, src/test/chain_tests.cpp
=> Add support for callbacks on tip change

qa/pull-tester/rpc-tests.py, qa/rpc-tests/32mb-bump.py, qa/rpc-tests/abc-monolith-activation.py, src/init.cpp, src/main.cpp, src/options.cpp, src/test/maxblocksize_tests.cpp, src/test/options_tests.cpp, src/utilfork.cpp, src/utilfork.h
=> Activation code for the third hard fork

qa/rpc-tests/mempool_limit.py, qa/rpc-tests/test_framework/util.py, qa/rpc-tests/txn_doublespendrelay.py
This should make the test more reliable on jenkins
=> [qa] Replace sleep with wait_for in mempool_limit

qa/rpc-tests/32mb-bump.py, qa/rpc-tests/test_framework/util.py, src/chain.cpp, src/chain.h, src/httpserver.cpp, src/httpserver.h, src/init.cpp, src/main.cpp, src/net.cpp, src/net.h, src/test/chain_tests.cpp
This is my take on https://reviews.bitcoinabc.org/D1285
=> [http] Scale request accept limit with block size

src/Makefile.am, src/consensus/tx_verify.cpp, src/consensus/tx_verify.h, src/main.cpp, src/main.h, src/miner.cpp, src/test/miner_tests.cpp, src/test/script_P2SH_tests.cpp, src/test/sighash_tests.cpp, src/test/sigopcount_tests.cpp, src/test/transaction_tests.cpp, src/txmempool.cpp, src/wallet/walletdb.cpp
https://github.com/bitcoin/bitcoin/pull/8329
Also replaced BOOST_FOREACH with C++11 for.
=> MOVEONLY: Move functions for tx verification

src/addrman.cpp, src/addrman.h, src/net.cpp, src/test/addrman_tests.cpp
bitcoin/bitcoin#9037
bitcoin/bitcoin#12622
This is designed to prevent a massive flood of fake peers from making us forget about helpful peers.
=> Add test-before-evict discipline to addrman

src/dbwrapper.h
=> Add SizeEstimate to CDBBatch

src/main.cpp
=> error in disconnect for disk corruption, not inconsistency

qa/rpc-tests/blockchain.py, src/coins.cpp, src/coins.h, src/dbwrapper.h, src/rpc/blockchain.cpp, src/txdb.cpp, src/txdb.h
On top of #392 and #396.
c3aa0c119 from Core#10195
Trivial merge.
=> Report on-disk size in gettxoutsetinfo

src/wallet/crypter.cpp
=> Fix crypter.cpp for OpenSSL 1.1 API

src/net.cpp, src/netbase.cpp, src/util.cpp
https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/1047
=> Correct Windows builds using the wrong FD_SETSIZE

src/coins.h, src/main.cpp, src/undo.h
422634e2f and cb2c7fdac from Core#10195
No conflicts.
=> Tx metadata in all undo records & new coins interface

src/coins.cpp, src/coins.h, src/main.cpp, src/rest.cpp, src/rpc/blockchain.cpp, src/txmempool.cpp, src/txmempool.h
On top of #415 
05293f3cb, 13870b56f and 4ec0d9e79 from Core#10195
Additional changes done in ProcessGetUTXOs (to continue to support BIP64)
=> Remove ModifyCoins, replace pruneSpent, refactor GetUTXOStats

src/coins.cpp, src/coins.h, src/consensus/tx_verify.cpp, src/main.cpp, src/test/coins_tests.cpp, src/txmempool.cpp, src/txmempool.h
3533fb4 and f58349c from https://github.com/bitcoin/bitcoin/pull/10537
https://github.com/bitcoin/bitcoin/pull/10558 - Address nits from per-utxo change
https://github.com/bitcoin/bitcoin/pull/10559 - Change semantics of HaveCoinInCache to match HaveCoin
https://github.com/bitcoin/bitcoin/pull/10581 - Simplify return values of GetCoin/HaveCoin(InCache)
=> Coins fixes

configure.ac, src/Makefile.am, src/Makefile.test.include, src/coins.h, src/secp256k1/Makefile.am, src/secp256k1/configure.ac, src/secp256k1/include/secp256k1_multiset.h, src/secp256k1/src/bench_multiset.c, src/secp256k1/src/modules/multiset/Makefile.am.include, src/secp256k1/src/modules/multiset/README.md, src/secp256k1/src/modules/multiset/main_impl.h, src/secp256k1/src/modules/multiset/tests_impl.h, src/secp256k1/src/secp256k1.c, src/secp256k1/src/tests.c, src/test/utxocommit_tests.cpp, src/utxocommit.cpp, src/utxocommit.h
Ported from: https://reviews.bitcoinabc.org/D1072
Reviewed by Amaury Sechet, Shammah Chancellor, Matias Garcia
This is preparational for the implementation of UTXO commitments.
Specification: https://github.com/tomasvdw/bips/blob/master/ecmh.mediawiki
=> Add ECMH UTXO commitments library and wrapper

src/main.cpp
Remove C++17 syntax that sneaked in.
=> Tuple syntax fix

src/main.cpp
Keep memory usage of coins cache within its limits
dd5862c from https://github.com/bitcoin/bitcoin/pull/6872 (modified to include getutxos)
=> Flush coins cache ofter

qa/rpc-tests/maxblocksinflight.py
https://github.com/bitcoin/bitcoin/pull/7803
=> [qa] maxblocksinflight: Actually enable test

qa/rpc-tests/test_framework/util.py
https://github.com/bitcoin/bitcoin/pull/9929
=> tests: Delete unused function _rpchost_to_args

qa/rpc-tests/fundrawtransaction.py, qa/rpc-tests/rpcbind_test.py, qa/rpc-tests/test_framework/util.py
https://github.com/bitcoin/bitcoin/pull/9824
=> qa: Check return code when stopping nodes

src/Makefile.am, src/Makefile.test.include, src/main.cpp, src/mempoolfeemodifier.cpp, src/mempoolfeemodifier.h, src/miner.cpp, src/rpc/mining.cpp, src/test/mempoolfeemodifier_tests.cpp, src/txmempool.cpp, src/txmempool.h, src/utilhash.cpp, src/utilhash.h
This moves the fee delta functionality to a helper class, with it's own
mutex. Less responsibility for CTxMempool class
On top of #457 #458
=>  Introduce MempoolFeeModifer

qa/rpc-tests/bip65-cltv-p2p.py, qa/rpc-tests/bip65-cltv.py, qa/rpc-tests/bipdersig-p2p.py, src/chainparams.cpp, src/consensus/params.h, src/main.cpp, src/rpc/blockchain.cpp
https://github.com/bitcoin/bitcoin/pull/8391
This also reverts 7ebe4208ddfd293611ff9e4f58ec274df8520ce2
=> Consensus: Remove ISM

src/consensus/validation.h, src/main.cpp, src/main.h
https://github.com/bitcoin/bitcoin/pull/5913
We already have the tests from https://github.com/bitcoin/bitcoin/pull/7179
=> Add absurdly high fee message to validation state

src/options.cpp, src/options.h, src/test/options_tests.cpp, src/test/utilfork_tests.cpp, src/utilfork.cpp, src/utilfork.h
Helper functions to check for upgrade activation. Triggers to clean mempool on activation/deactivation. 
Also includes a _revert me_ commit, that when reverted, enables the upgrade by default.
=> [fork] Helper functions and mempool triggers

qa/rpc-tests/bip9-softforks.py, qa/rpc-tests/test_framework/test_framework.py, qa/rpc-tests/test_framework/util.py, src/main.cpp, src/main.h, src/rpc/blockchain.cpp, src/rpc/mining.cpp, src/versionbits.cpp, src/versionbits.h
https://github.com/bitcoin/bitcoin/pull/7935 GBT support for bip9
https://github.com/bitcoin/bitcoin/pull/7863 Make bip9_softforks an object
Required for next update to #477.
=> bip9 cherries 

qa/rpc-tests/bip100-sizelimit.py
Support bitcoinxt#488. 
Also increase timeouts during cache rebuild.  For some reason my local machine needs a bit more time for this now.
=> [qa] bip100-sizelimit test updates

src/script/interpreter.cpp, src/script/script.cpp, src/script/script.h, src/test/sigopcount_tests.cpp
https://github.com/bitcoin/bitcoin/pull/6818 - script: Remove magic numbers
Modified commit of fdb43df from https://github.com/bitcoin/bitcoin/pull/8149 (segwit counting removed)
=> SigOp count test

qa/pull-tester/rpc-tests.py, qa/rpc-tests/abc-magnetic-anomaly-activation.py, qa/rpc-tests/abc-monolith-activation.py, qa/rpc-tests/abc-transaction-ordering.py, qa/rpc-tests/bip68-sequence.py, qa/rpc-tests/mempool_reorg.py, qa/rpc-tests/p2p-compactblocks.py, qa/rpc-tests/p2p-fullblocktest.py, qa/rpc-tests/rawtransactions.py, qa/rpc-tests/test_framework/blocktools.py, qa/rpc-tests/test_framework/cdefs.py, qa/rpc-tests/test_framework/txtools.py, src/Makefile.am, src/checkqueue.h, src/consensus/consensus.h, src/main.cpp, src/main.h, src/miner.cpp, src/qt/transactiondesc.cpp, src/qt/transactionrecord.cpp, src/script/interpreter.h, src/test/coins_tests.cpp, src/test/miner_tests.cpp, src/test/script_P2SH_tests.cpp, src/test/transaction_tests.cpp, src/txmempool.cpp, src/wallet/finaltx.cpp, src/wallet/finaltx.h, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp
https://reviews.bitcoinabc.org/D144
https://reviews.bitcoinabc.org/D1611
=> [fork] Impose a minimum transaction size of 100 bytes
