bitcoinxt/bitcoinxt

qa/rpc-tests/doublespendrelay.py, src/init.cpp, src/qt/transactiontablemodel.cpp
- Clean up "todo" comments relating to alert dialog, this was "todone".
- Update double-spend regtest to conform to changes in framework
- Add back missing help text on -respendnotify option
=> Double-spend relay fixes

src/net.cpp
Currently in XT the network socket is read in only 8 byte chunks.
The code
char *pchBuf = new char[amt];
int nBytes = recv(pnode->hSocket, pchBuf, sizeof(pchBuf), MSG_DONTWAIT);
is equivalent to
char *pchBuf = new char[amt];
int nBytes = recv(pnode->hSocket, pchBuf, 8, MSG_DONTWAIT);
This wastes CPU and dramatically reduces transfer speed for all network communication.
Fixing the bug on my LAN testnet setup increases block transfer speed 3 times.
Bug does not affect the other implementation.
=> Fix socket buffer bug

src/bloom.cpp, src/bloom.h, src/main.cpp, src/net.cpp, src/test/bloom_tests.cpp
A live DoS attack observed by several nodes in recent days involved repeated rejection of duplicate transactions.
The first six commits to address this problem have already been merged in core bitcoin/bitcoin#6498.  A rolling bloom filter tracks recently rejected transactions to avoid repeatedly requesting them from peers and re-checking them.
The last commit adds a call to AlreadyHave when an *unsolicited* full tx is received, as was the case in the observed attack.  AlreadyHave uses the recentRejects filter.
I tested all of these changes on mainnet while the actual attack was still underway.
The recentRejects filter is cleared when the tip is updated, so nothing stops attacker from re-transmitting a load of rejectable txes after a new block, and in fact our attacker was doing this.  But …
=> Track recently rejected transactions; don't reprocess

src/Makefile.am, src/Makefile.test.include, src/clientversion.cpp, src/clientversion.h, src/init.cpp, src/main.cpp, src/main.h, src/net.cpp, src/options.cpp, src/options.h, src/test/clientversion_tests.cpp
This was requested on the mailing list a while ago.
Requires boost 1.55. Feature is disabled if older boost. I don't think the complexity of implementing this without boost is worth it.
If adding the Opt class is overdoing it, I can redo this PR without it and the unittests.
I have so far only compiled on Linux.
Screenshot:
=> Add platform details to comment section of user agent.

qa/rpc-tests/bip65-cltv.py, qa/rpc-tests/forknotify.py
On some systems, bip65-cltv.py fails because the default 200 BIP101-version blocks are mined before the test begins, causing it to think BIP65 is already in effect.
@error10 does applying this 7-line change fix issue #101 for you?
=> Fix blockversion race condition in two regtests

qa/rpc-tests/pruning.py
In my ever-growing list of test failures, I was seeing this one intermittently.
```
Running 2nd level testscript pruning.py...
Initializing test directory /tmp/testY5ypCv
Warning! This test requires 4GB of disk space and takes over 30 mins (up to 2 hours)
Mining a big blockchain of 995 blocks
Check that we haven't started pruning yet because we're below PruneAfterHeight
Success
Though we're already using more than 550MB, current usage: 587
Mining 25 more blocks should cause the first block file to be pruned
Assertion failed: blk00000.dat not pruned when it should be
File "/home/error/bitcoinxt-0.11D/qa/rpc-tests/test_framework/test_framework.py", line 118, in main
self.run_test()
File "/home/error/bitcoinxt-0.11D/qa/rpc-tests/pruning.py", line 272, in run_test
self.test_height_min()
File …
```
=> Increase timeout waiting for pruned blk00000.dat

src/net.cpp
When the sendshaper is on and the outgoing
traffic is pegged to the upper speed limit
then cpu will go to 90% on one core.
The best way I've found to see this is to:
1) get the node running first with no traffic shaping and let it stabilize for about 15 minutes
2) set the outbound traffic shaping way down to about 10 or 15KB but have no inbound traffic shaping
3)  wait for the outbound traffic to be pegged at the upper limit you've set.  Once it's pegged there the cpu will start to race, using up about 90% on one core.
The system must be busy to see this.  ( It's harder on a sunday afternoon to get this problem to appear)
=> Fix for busy wait loop in SendShaper

src/Makefile.am, src/Makefile.test.include, src/clientversion.cpp, src/clientversion.h, src/init.cpp, src/main.cpp, src/main.h, src/net.cpp, src/net.h, src/options.cpp, src/options.h, src/test/clientversion_tests.cpp
This PR is an alternative implementation of #69 
This one is compatible with #98. Also, compared to #69 it does not add a global subversion variable, has a unit test and --help text.
=> Implement uacomment (alternative to #69)

src/net.cpp
Pruned node would show NODE_NETWORK service bit when in stealth mode.
=> Dont claim NODE_NETWORK support in stealth mode unless the node supports it

src/wallet/walletdb.cpp
This fix is important to me because the combination of debug settings and -salvagewallet is helpful in testing double-spends.
=> [walletdb] Add missing LOCK() in Recover() for dummyWallet

src/main.cpp
This is required to serve thin blocks.
We accept the same 1e-6 false-positive rate that is already accepted in the other places the known-inventory filter is used (eg RelayTransaction).
The filter was disabled in core version 0.12 by https://github.com/bitcoin/bitcoin/commit/ec73ef37eccfeda76de55c4ff93ea54d4e69e1ec.
=> Re-enable known-inventory filter in merkleblock

src/qt/transactiondesc.cpp, src/qt/transactionrecord.cpp
Big diff from modifying the main conditional, but actually only a few lines changed. I just got rid of the first "if (nNet > 0 || wtx.IsCoinBase())" statement, fixed the indentation, and moved the "// Credit" section down into an "else if (fAllToMe)" block. Then added a comment where the coinjoins are caught. Thats all.
This fixes the transaction list so that it shows 1 row per transaction instead of 2 for coinjoins, and for the amount shows the transaction Net value. More importantly, this fixes the details view for coinjoin transactions so that Debits and Credits are shown accurately, allowing one to discern what Debits and Credits were theirs in this transaction.
=> Display coinjoins properly in QT

src/leveldb/util/env_win.cc
Reduces the incidence of corruption requiring reindex on the Windows platform.
This is bitcoin/leveldb#9.
=> LevelDB fix to reduce corruption after crashes

src/main.cpp
Fixes a bug where a thin block pong is interpreted as a regular pong.
This caused the block download to time out.
=> Support waiting for regular pong and thin block pong at the same time.

src/txmempool.cpp
Negating a size_t and assigning to int64_t does not work with < 64-bit compile platform.
=> Fix compile-platform-dependent mempool bug

contrib/gitian-debian/README.md, contrib/gitian-debian/build.sh
@dgenr8 I tested updated gitian-debian build instructions and upgrade installation on Debian 8 VM.  New 0.11E package installed and started daemon with no errors.
=> #128 Updated gitian-debian build script and README.md to version 0.11E

src/qt/transactiondesc.cpp, src/qt/transactionrecord.cpp
Reverts bitcoinxt/bitcoinxt#121
This had unintended consequences, and @raedah has stopped working it. More detail in #121.
=> Revert "Display coinjoins properly in QT"

src/init.cpp, src/timedata.cpp, src/timedata.h
remove -trustsystemclock and add -maxtimeadjustment with default of 0 instead of the 4200 used upstream.
for reference:
https://github.com/bitcoinxt/bitcoinxt/pull/35
https://github.com/bitcoin/bitcoin/pull/7573
=> remove -trustsystemclock and add -maxtimeadjustment with default of 0

src/thinblock.h, src/thinblockmanager.h, src/utilprocessmsg.h, src/xthin.h
Several types were declared as structs (presumably to save a `public:` line), but were forward-declared throughout the code as classes.
I changed them back to `class` since it seemed like the path of least resistance (otherwise all the forward declarations would have to be changed).
=> Fix class/struct mismatches

qa/pull-tester/rpc-tests.sh, qa/rpc-tests/spv.py, qa/rpc-tests/test_framework/mininode.py, qa/rpc-tests/test_framework/murmurhash.py, src/bloom.h, src/main.cpp, src/net.cpp, src/net.h, src/rpcrawtransaction.cpp, src/txmempool.cpp, src/txmempool.h, src/wallet/wallet.cpp
Lets an SPV peer better track the confirmation process of wallet transactions by knowing details about unconfirmed ancestors.
Connection bloom filter nFlags bit ``BLOOM_ANCESTOR_UPDATE_BIT = 4`` is newly defined to mean that the SPV peer wants its filter be automatically updated with the txids of unconfirmed ancestors of transactions that are already contained in the filter.
Filter update with unconfirmed ancestors occurs in the two places that filtered results for unconfirmed transactions are provided: transaction relay, and the "mempool" p2p response.  The results also include the ancestors added.
SPV "merkleblock" response is indirectly enhanced, because the filter will contain id's for transactions that were at some point seen as unconfirmed ancestors of a wallet transaction. …
=> SPV: Push unconfirmed ancestors to peer. SPV test.

src/ipgroups.cpp, src/ipgroups.h, src/main.cpp, src/net.cpp, src/net.h, src/test/ipgroups_tests.cpp, src/test/net_tests.cpp
The goal is to force an attacker to spread out with multiple IPs
to exaust connection slots, making the attack more expensive.
This is done by creating a single-ip-ipgroup for every node that does
not belong to any other ipgroups. For every new connection from the same
ip, that group gets lower priority. When a node disconnects, the
priority increases again.
=> De-prioritize IPs with 2 or more connections.

src/init.cpp, src/main.cpp, src/main.h, src/test/alert_tests.cpp
Two corrections are made to the bad-chain alert triggering mechanism: oversampling is eliminated and the test is changed to make correct use of the poisson CDF.
Overall, the effect will be for the alert to trigger less often, since it was triggering too easily before.
There has been review and discussion at https://github.com/bitcoin/bitcoin/pull/7568.  The holdup there seems to be that this doesn't fix everything.  No disagreement that it's a big improvement.
=> Corrections to bad-chain alert triggering

src/blocksender.cpp, src/main.cpp, src/net.h
I encountered a deadlock in testing due to reuse of CNode::cs_filter to protect xthinFilter.  This pull introduces a dedicated lock cs_xfilter for this purpose.
=> Don't use CNode::cs_filter to protect xthinFilter

src/main.cpp
This is a backport of bitcoin/bitcoin#6148. Had to replace `chainparams.GetConsensus().nPowTargetSpacing` with `Params().GetConsensus().nPowTargetSpacing` inside `ProcessMessage` function to fix a compilation error.
=> Block relaying in pruned mode

depends/packages/boost.mk
Release G will include several dependency version bumps.  This fixes a known bug with one of them.
=> [depends] Boost 1.61.0

src/qt/bitcoingui.cpp, src/qt/bitcoingui.h, src/qt/forms/optionsdialog.ui, src/qt/optionsdialog.cpp, src/qt/optionsdialog.h, src/qt/optionsmodel.cpp, src/qt/optionsmodel.h
This is a cherry-pick from Bitcoin Core. I'm requesting it be merged in here because a) I'm getting odd tray icon behaviour with the official builds on Ubuntu/Unity and b) I've got enough tray icons already.
Merged cleanly and works in my informal tests on Ubuntu.
=> Qt: Add option to hide the system tray icon

src/init.cpp, src/main.h, src/rpcblockchain.cpp
Cherry-pick of https://github.com/bitcoin/bitcoin/pull/8611.
This speeds startup by reducing the default number of recent blocks to re-check.
=> Reduce default number of blocks to check at startup

src/test/options_tests.cpp
Check wrongly assumes >= 2 CPU cores.
=> Remove a check in scripthreads test

qa/rpc-tests/bip9-softforks.py, qa/rpc-tests/mempool_resurrect_test.py, qa/rpc-tests/mempool_spendcoinbase.py, qa/rpc-tests/merkle_blocks.py, qa/rpc-tests/test_framework/comptool.py, qa/rpc-tests/wallet.py, src/consensus/validation.h, src/init.cpp, src/main.cpp, src/main.h, src/miner.cpp, src/test/mempool_tests.cpp, src/test/miner_tests.cpp, src/test/test_bitcoin.cpp, src/test/test_bitcoin.h, src/txmempool.cpp, src/txmempool.h
Based on https://github.com/bitcoin/bitcoin/pull/6898 by @morcos which appeared in core 0.12.0.
Use the fee score index on the mempool to add transactions to a new block in sorted order.  XT's mempool policy, which strongly discourages unconfirmed chains by expecting a child to pay for all unconfirmed ancestors, is extended to CreateNewBlock by mining these paid-for ancestors.
Removes much of the validation while building the block, relying on mempool to be consistent and only contain txs that can be mined.
The old "priority" block area is removed and minimum block size is no longer supported.
Individual transactions may be excluded by setting a fee delta that drops them below ::MinRelayFee, as expected by tests.  The -relaypriority=0 argument is supported as a way to cause free or …
=> Rewrite CreateNewBlock

src/bitcoin-cli.cpp, src/bitcoin-tx.cpp, src/bitcoind.cpp, src/chainparams.cpp, src/chainparams.h, src/chainparamsbase.cpp, src/chainparamsbase.h, src/checkpoints.h, src/consensus/params.h, src/init.cpp, src/main.cpp, src/miner.cpp, src/qt/bitcoin.cpp, src/rpcserver.cpp, src/test/Checkpoints_tests.cpp, src/test/miner_tests.cpp
Backports for chainparams. This is in preparation for adding a new testnet.
Built on top of PR https://github.com/bitcoinxt/bitcoinxt/pull/188
Includes the following PRs:
https://github.com/bitcoin/bitcoin/pull/6222
https://github.com/bitcoin/bitcoin/pull/6370
https://github.com/bitcoin/bitcoin/pull/6398
https://github.com/bitcoin/bitcoin/pull/6381
https://github.com/bitcoin/bitcoin/pull/6242
https://github.com/bitcoin/bitcoin/pull/6473
https://github.com/bitcoin/bitcoin/pull/6235
https://github.com/bitcoin/bitcoin/pull/6931
https://github.com/bitcoin/bitcoin/pull/7128
=> Chainparams backports

src/net.cpp
Core continues to support compact blocks v1 after segwit activation (this was not the case when this check was added).
(Original commit: https://github.com/rebroad/bitcoinxt/commit/81d7d605f88dadfbe995149c0689ce67b4127531)
=> Don't ignore nodes advertising SEGWIT

doc/REST-interface.md, qa/rpc-tests/rest.py, qa/rpc-tests/wallet.py, src/rest.cpp, src/rpcblockchain.cpp, src/rpcnet.cpp, src/rpcserver.cpp, src/test/rpc_tests.cpp, src/test/univalue_tests.cpp, src/test/util_tests.cpp, src/univalue/univalue.cpp, src/univalue/univalue.h, src/univalue/univalue_write.cpp, src/utilmoneystr.cpp, src/utilmoneystr.h, src/utilstrencodings.cpp, src/utilstrencodings.h, src/wallet/rpcwallet.cpp
Patch to accept strings containing decimal value + other fixes leading up to it in Core.
Contains these PRs:
https://github.com/bitcoin/bitcoin/pull/5486/ - [REST] JSON support for /rest/headers
https://github.com/bitcoin/bitcoin/pull/6239/ - Don't go through double in AmountFromValue and ValueFromAmount
https://github.com/bitcoin/bitcoin/pull/6362/ - Fix null id in RPC response during startup
https://github.com/bitcoin/bitcoin/pull/6379/ - rpc: Accept scientific notation for monetary amounts in JSON
https://github.com/bitcoin/bitcoin/pull/6456/ - rpc: Avoid unnecessary parsing roundtrip in number formatting, fix locale issue
https://github.com/bitcoin/bitcoin/pull/6380/ - rpc: Accept strings in AmountFromValue
=> rpc: Accept strings in AmountFromValue

src/blockannounce.cpp, src/blockannounce.h, src/blocksender.cpp, src/main.cpp, src/nodestate.cpp, src/nodestate.h, src/test/blockannounce_tests.cpp, src/utilprocessmsg.cpp, src/utilprocessmsg.h
Adds support for announcing blocks using compact blocks instead of inv or header. Remote node must requests "high bandwith mode" compact blocks to enable this.
Note: XT does not request block announcements yet, but can now serve them.
=> Announce blocks with compact blocks

src/blockannounce.cpp, src/blockheaderprocessor.cpp, src/blockheaderprocessor.h, src/blockprocessor.cpp, src/blockprocessor.h, src/compactblockprocessor.cpp, src/main.cpp, src/nodestate.cpp, src/nodestate.h, src/process_merkleblock.cpp, src/process_xthinblock.cpp, src/test/blockannounce_tests.cpp, src/test/blockheaderprocessor_tests.cpp, src/test/processmessage_tests.cpp
Always request preceding headers for headers, blocks and thinblocks received. If preceding headers were missing, discard the received block (to be downloaded again later, if we still want it). 
This is mostly done already, but in a more ad-hoc fasion, so this simplifies the code.
=> Generic method to request preceding headers.

doc/developer-notes.md, src/Makefile.test.include, src/init.cpp, src/miner.cpp, src/net.cpp, src/options.cpp, src/qt/optionsdialog.cpp, src/test/getarg_tests.cpp, src/test/test_bitcoin.cpp, src/test/testutil.cpp, src/test/testutil.h, src/tinyformat.h, src/util.cpp, src/util.h
Misc PRs from Core related to util.cpp/util.h
https://github.com/bitcoin/bitcoin/pull/6164 - Allow user to use -debug=1 to enable all debugging
https://github.com/bitcoin/bitcoin/pull/6361 - Use real number of cores for default -par, ignore virtual cores
https://github.com/bitcoin/bitcoin/pull/6149 - Buffer log messages and explicitly open logs
https://github.com/bitcoin/bitcoin/pull/6438 - openssl: avoid config file load/race
https://github.com/bitcoin/bitcoin/pull/6284 - Fix argument parsing oddity with -noX
https://github.com/bitcoin/bitcoin/pull/6742 - Changed logging to make -logtimestamps to work also for -printtoconsole
https://github.com/bitcoin/bitcoin/pull/7114 - util: Don't set strMiscWarning on every exception
https://github.com/bitcoin/bitcoin/pull/7667 - Move GetTempPath() …
=> Util ports

src/tinyformat.h, src/util.h
Contains the following in addition to a variable rename
https://github.com/bitcoin/bitcoin/pull/9417 - Do not evaluate hidden LogPrint arguments
https://github.com/bitcoin/bitcoin/pull/9963 - util: Properly handle errors during log message formatting
Useful for finding errors in use of LogPrint
=> Don't throw LogPrint errors

qa/rpc-tests/txn_doublespendrelay.py, src/wallet/wallet.cpp
The test txn_doublespendrelay is randomly failing.
After investigating I can see that the double spend reporting works, however transactions some times take a very long time to be passed between nodes.
Increasing the timeout makes the test pass. I have yet to find out why transactions are slow to be passed between nodes.
This PR also makes the rpc test state explicitly when it fails due to timeout.
=> Increase timeout in txn_doublespendrelay

src/init.cpp, src/options.cpp, src/options.h
Signed int64_t is used to allow possible special values as negative numbers, for example a way to specify the default activation time per spec, if we should change our default to 0 or create a second release that does so.
=> UAHF: REQ-1, REQ-2, REQ-DISABLE. Activation time option, default enabled.

src/consensus/consensus.h, src/init.cpp, src/main.cpp, src/maxblocksize.cpp, src/options.cpp, src/options.h, src/test/maxblocksize_tests.cpp
We bump the block size to 8MB with the fork block, and simultaneously activate BIP100.
Depending on where in the difficulty interval the fork occurs, a BIP100 max size change is theoretically possible at the next retargeting.
bip100-sizelimit.py hasn't been updated.  We need an efficient way to create ~8M blocks.
=> UAHF: REQ 4-1. Max block size increase to 8M.

src/consensus/consensus.h, src/init.cpp, src/main.cpp, src/options.cpp, src/options.h, src/test/sigopcount_tests.cpp
Per UAHF spec, limit all transactions to 20k legacy sigops.
=> UAHF: SPEC max 20k legacy sigops / tx

src/Makefile.test.include, src/init.cpp, src/main.cpp, src/main.h, src/options.cpp, src/options.h, src/script/script.cpp, src/script/script.h, src/test/script_antireplay_tests.cpp
REQ-6-1 This-chain replay protection.
Disallow a special OP_RETURN commitment, to enable transactions to be protected from execution on the UAHF chain.  A configurable sunset height is set to the specified default of 530000.
=> UAHF: REQ 6-1 This-chain replay protection

src/init.cpp, src/options.cpp, src/options.h, src/pow.cpp, src/test/pow_tests.cpp
Between regular adjustments, difficulty drops 20% when timestamp difference >= 12 hours is seen across 6 block intervals.
=> UAHF: REQ-7 Difficulty adjustement in case of hashrate drop

src/init.cpp, src/main.cpp, src/options.cpp, src/options.h
Require the fork block (first block built on a block with MTP >= UAHF activation time) to be >1MB in size, as "wipeout protection" and for upgrade predictability.
=> UAHF: REQ-3. Fork block must be > 1MB.

src/blockencodings.cpp, src/main.cpp, src/maxblocksize.cpp, src/maxblocksize.h, src/test/ReceiveMsgBytes_tests.cpp, src/test/maxblocksize_tests.cpp, src/test/xthin_tests.cpp
DoS limits for block size was adjusted for BIP100, but not a sudden jump to 8MB.
=> UAHF: Adjust block size DoS limit

qa/pull-tester/rpc-tests.py, qa/rpc-tests/bip100-sizelimit.py, qa/rpc-tests/bip65-cltv-p2p.py, qa/rpc-tests/bip68-112-113-p2p.py, qa/rpc-tests/bip68-sequence.py, qa/rpc-tests/bip9-softforks.py, qa/rpc-tests/bipdersig-p2p.py, qa/rpc-tests/mempool_packages.py, qa/rpc-tests/mempool_reorg.py, qa/rpc-tests/mempool_resurrect_test.py, qa/rpc-tests/mempool_spendcoinbase.py, qa/rpc-tests/merkle_blocks.py, qa/rpc-tests/rawtransactions.py, qa/rpc-tests/signrawtransactions.py, qa/rpc-tests/smartfees.py, qa/rpc-tests/spv.py, qa/rpc-tests/test_framework/util.py, qa/rpc-tests/txn_clone.py, qa/rpc-tests/txn_doublespend.py, qa/rpc-tests/txn_doublespendrelay.py, qa/rpc-tests/wallet.py, src/Makefile.am, src/bitcoin-tx.cpp, src/main.cpp, src/options.cpp, src/rpcrawtransaction.cpp, src/test/DoS_tests.cpp, src/test/multisig_tests.cpp, src/test/rpc_tests.cpp, src/test/script_P2SH_tests.cpp
In regtest, default UAHF activation to the genesis block, and relax the requirement to mine a big fork block when the UAHF activation is set to the new default.
Revert earlier RPC test changes that were aimed at generating non-SIGHASH_FORKID transactions.  All RPC tests now run with the new BIP143-derived signature hashing scheme.
Remove the bipdersig test as the UAHF requires STRICTENC by consensus.
=> REGTEST: Run all tests in a post-fork environment

qa/pull-tester/rpc-tests.py, qa/rpc-tests/invalidblockrequest.py, qa/rpc-tests/invalidtxrequest.py, qa/rpc-tests/test_framework/comptool.py
I cherry-picked this to get the class comptool.RejectResult, which is a prerequisite for a rpc test I'm porting for Bitcoin ABC.
As a bonus this also contains a couple of bug fixes and a new rpc test, invalidtxrequest.py.
Contains commits from:
https://github.com/bitcoin/bitcoin/pull/6465 - Don't share objects between TestInstances
https://github.com/bitcoin/bitcoin/pull/6509 - Fix race condition on test node shutdown
https://github.com/bitcoin/bitcoin/pull/7179 - net: Fix sent reject messages for blocks and transactions
=> Add comptool.RejectResult

qa/rpc-tests/mempool_limit.py, qa/rpc-tests/pruning.py
This XT-specific test was missed in #237.
=> Fix mempool_limit test - sign with FORKID

src/maxblocksize.cpp
In a UAHF context we can no longer expect the max block size to be constant within an arbitrary diff interval.
=> Remove BIP100 assert

src/blockheaderprocessor.cpp, src/blockheaderprocessor.h, src/test/blockheaderprocessor_tests.cpp
Fetch the oldest blocks missing when direct fetching during a header
announcement. Added unittests.
This is a workaround for rpc-test issue described here: https://github.com/bitcoinxt/bitcoinxt/pull/243#issuecomment-322727048
`bip9-softforks` does not randomly fail after this fix.
=> Direct fetch in order

src/qt/test/uritests.cpp
UAHF status is checked to determine if prefix is `bitcoin:` or `bitcoincash:`. This requires chainparams to be initialized.
Regression was in https://github.com/bitcoinxt/bitcoinxt/pull/248
=> [qt] initialize chainparams in uri test

src/maxblocksize.cpp, src/test/maxblocksize_tests.cpp
Two changes to the bip100 implementation.
1 - Remove null check on pIndexLast->pprev in GetNextMaxBlockSize().  This is part of the job of IsUAHFActivatingBlock() which handles the regtest case, that activates at genesis.
2 - The default max block size vote should be the end-of-interval value, not the value as of the voting block. This can make a difference if some rare event like the UAHF modifies the max block size within the interval.
In the actual UAHF, it did not matter, because the fork occurred with fewer than 75% voting (by default) for a size different than the end-of-interval size (8M).
=> BIP100 cleanup for regtest, theoretical fork

contrib/gitian-debian/postinst, contrib/gitian-debian/templates
User is asked to select which network (BCC or BTC) to connect to when
installing the debian package.
=> [debian] Add configuration step to select network

qa/rpc-tests/getblocktemplate_longpoll.py, qa/rpc-tests/getblocktemplate_proposals.py, qa/rpc-tests/keypool.py, qa/rpc-tests/listtransactions.py, qa/rpc-tests/receivedby.py, qa/rpc-tests/test_framework/util.py, src/init.cpp, src/miner.cpp, src/miner.h, src/rpcmining.cpp, src/rpcserver.cpp, src/script/script.h, src/validationinterface.cpp, src/validationinterface.h, src/wallet/wallet.cpp, src/wallet/wallet.h
Ports of the following:
https://github.com/bitcoin/bitcoin/pull/5994 - detach wallet from miner
https://github.com/bitcoin/bitcoin/pull/6567 - Fix crash when mining with empty keypool.
https://github.com/bitcoin/bitcoin/pull/7027 - [qa] rpc-tests: Properly use test framework
fa942c7 (Move method to check matches within arrays on util.py) from https://github.com/bitcoin/bitcoin/pull/7822/
Builds on top of #257
=> keypool test bump + detach wallet from miner

src/chainparams.cpp, src/chainparams.h, src/main.cpp, src/main.h
Regtest is changed to have the old blockfile size of 128MB instead of the post-fork size of 1024MB, so the tuned string of tests in pruning.py continues to work.
This fixes issue #256.
=> Fix pruning.py failure with default 8MB

qa/pull-tester/rpc-tests.py, qa/rpc-tests/bip100-sizelimit.py, qa/rpc-tests/mempool_limit.py, qa/rpc-tests/pruning.py, qa/rpc-tests/test_framework/util.py
Update bip100-sizelimit.py to run in the post-uahf (Bitcoin Cash fork) regtest environment.  Include cherry-picks that factor out standard big block and transaction routines, and use those routines.
=> [Test] Update bip100-sizelimit.py for uahf

qa/rpc-tests/test_framework/mininode.py, src/Makefile.test.include, src/chainparams.cpp, src/chainparams.h, src/main.cpp, src/net.cpp, src/test/ReceiveMsgBytes_tests.cpp, src/test/chainparams_tests.cpp, src/test/net_tests.cpp
This changes the network magic bytes when the node runs on the Bitcoin Cash network.
These bytes were also used in the database. For backward compatibility, we still use the old byte values for database.
This change is not backward compatible with older nodes. This is fine, since we're doing a hard fork in a few days.
=> Use Bitcoin Cash network magic

qa/rpc-tests/walletbackup.py, src/wallet/walletdb.cpp
From https://github.com/bitcoin/bitcoin/pull/11376
Previous behaviour was to destroy the wallet (to zero-length)
=> Ensure backupwallet fails if pathDest is set to pathSource

src/thinblock.cpp
Make it safe to modify the blocks set during iteration.
=> Take a copy of blocks in stopAllWork

src/dbwrapper.h
https://github.com/bitcoin/bitcoin/pull/9346
Also includes commit d59a518 from https://github.com/bitcoin/bitcoin/pull/9039
Build on top of #276
=> Batch construct batches

qa/pull-tester/rpc-tests.py, qa/rpc-tests/fundrawtransaction.py, qa/rpc-tests/listtransactions.py, qa/rpc-tests/rawtransactions.py, src/coincontrol.h, src/keystore.cpp, src/keystore.h, src/primitives/transaction.h, src/qt/coincontroldialog.cpp, src/qt/sendcoinsdialog.cpp, src/qt/transactiondesc.cpp, src/qt/transactionrecord.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/rpcclient.cpp, src/rpcserver.cpp, src/rpcserver.h, src/script/sign.cpp, src/script/sign.h, src/script/standard.cpp, src/script/standard.h, src/test/rpc_wallet_tests.cpp, src/test/script_tests.cpp, src/wallet/crypter.cpp, src/wallet/rpcdump.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/wallet_ismine.cpp, src/wallet/wallet_ismine.h
Adds fundrawtransaction RPC call. Includes the following from Bitcoin Core:
https://github.com/bitcoin/bitcoin/pull/6088 - fundrawtransaction
https://github.com/bitcoin/bitcoin/pull/6417 - [QA] fix possible reorg issue in (fund)rawtransaction(s).py RPC test
https://github.com/bitcoin/bitcoin/pull/6444 - Exempt unspendable transaction outputs from dust checks
https://github.com/bitcoin/bitcoin/pull/6415 - Implement watchonly support in fundrawtransaction
https://github.com/bitcoin/bitcoin/pull/6828 - [rpc-tests] fundrawtransaction: Update fee after minRelayTxFee increase
commit bebe58 from https://github.com/bitcoin/bitcoin/pull/7296
https://github.com/bitcoin/bitcoin/pull/7506 - Use CCoinControl selection in CWallet::FundTransaction
https://github.com/bitcoin/bitcoin/pull/7518 - Add …
=> Add fundrawtransaction

src/Makefile.bench.include, src/bench/rollingbloom.cpp, src/bloom.cpp, src/bloom.h, src/test/bloom_tests.cpp, src/test/util_tests.cpp
* Improve rolling bloom filter performance - https://github.com/bitcoin/bitcoin/pull/7934/             
* trivial: fix bloom filter init to isEmpty = true - https://github.com/bitcoin/bitcoin/pull/9060      
* Bloomfilter: parameter variables made constant - https://github.com/bitcoin/bitcoin/pull/9750        
* Fix msvc compiler error C4146 (minus operator applied to unsigned type) - https://github.com/bitcoin/bitcoin/pull/9916
=> Bloom filter updates

qa/rpc-tests/fundrawtransaction.py, src/base58.cpp, src/base58.h, src/bitcoin-tx.cpp, src/core_write.cpp, src/qt/addresstablemodel.cpp, src/qt/bitcoinaddressvalidator.cpp, src/qt/coincontroldialog.cpp, src/qt/guiutil.cpp, src/qt/paymentserver.cpp, src/qt/sendcoinsdialog.cpp, src/qt/signverifymessagedialog.cpp, src/qt/transactiondesc.cpp, src/qt/transactionrecord.cpp, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/rpcmisc.cpp, src/rpcrawtransaction.cpp, src/script/standard.cpp, src/script/standard.h, src/test/base58_tests.cpp, src/test/key_tests.cpp, src/test/rpc_wallet_tests.cpp, src/wallet/rpcdump.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/walletdb.cpp
Includes changes from:
https://github.com/bitcoin/bitcoin/pull/11247 - Partial cherry-pick to get IsSpendable
https://github.com/bitcoin/bitcoin/pull/11117 - Prepare for non-Base58 addresses
https://github.com/bitcoin/bitcoin/pull/11259 - Remove duplicate destination decoding
This is a prerequisite to supporting cashaddr.
=> Prepare for non-Base58 addresses

src/Makefile.am, src/Makefile.test.include, src/blockannounce.h, src/bloom.cpp, src/bloom.h, src/init.cpp, src/main.cpp, src/options.cpp, src/options.h, src/respend/respendaction.h, src/respend/respenddetector.cpp, src/respend/respenddetector.h, src/respend/respendlogger.cpp, src/respend/respendlogger.h, src/respend/respendrelayer.cpp, src/respend/respendrelayer.h, src/respend/test/respenddetector_tests.cpp, src/respend/test/respendrelayer_tests.cpp, src/respend/test/walletnotifier_tests.cpp, src/respend/walletnotifier.cpp, src/respend/walletnotifier.h, src/utilprocessmsg.cpp, src/utilprocessmsg.h
This moves logic for handling double spends out of AcceptToMemoryPool. Each distinct action (relay, notify wallet, logging) is implemented as a separate "respend action". 
Unit test coverage is added for all features.
This also improves logging (enable with debug=respend) and fixes an issue where notification to wallet would be stopped by the relay limiter. The relay filter is replaced with a rolling bloom filter.
This will make it easier to add additional features such as https://github.com/bitcoinxt/bitcoinxt/issues/246 or RPC notifications on respends. New features can be added by implementing the _RespendAction_ interface.
=> Framework for handling double spends

qa/rpc-tests/httpbasics.py, src/httpserver.cpp, src/httpserver.h, src/init.cpp, src/rpcserver.cpp
https://github.com/bitcoin/bitcoin/pull/6719 - Make HTTP server shutdown more graceful                
https://github.com/bitcoin/bitcoin/pull/6859 - http: Restrict maximum size of http + headers          
https://github.com/bitcoin/bitcoin/pull/6990 - http: speed up shutdown                                
https://github.com/bitcoin/bitcoin/pull/7966 - http: Do a pending c++11 simplification handling work items
https://github.com/bitcoin/bitcoin/pull/8421 - httpserver: drop boost (#8023 dependency)              
https://github.com/bitcoin/bitcoin/pull/11006 - Improve shutdown process
=> HTTP Server cherries

qa/rpc-tests/test_framework/mininode.py, qa/rpc-tests/test_framework/test_framework.py, qa/rpc-tests/test_framework/util.py
https://github.com/bitcoin/bitcoin/pull/8047 - [qa] test_framework: Set wait-timeout for bitcoind procs
https://github.com/bitcoin/bitcoin/pull/8098 - [qa] test_framework: Append portseed to tmpdir
https://github.com/bitcoin/bitcoin/pull/8095 - Test framework: only cleanup on successful test runs
https://github.com/bitcoin/bitcoin/pull/8214 - [qa] mininode: fail on send_message instead of silent return
=> QA cherries

qa/rpc-tests/txn_clone.py, qa/rpc-tests/txn_doublespend.py, src/Makefile.am, src/init.cpp, src/respend/mempoolremover.cpp, src/respend/mempoolremover.h, src/respend/respenddetector.cpp, src/respend/respendlogger.cpp, src/txmempool.cpp
Reuse the new framework and avoid the need to repeat logging in CTxMemPool::removeConflicts(...)
Functional test `txn_doublespend.py` should succeed and log the respend found in a block, while `txn_clone.py` should succeed and not log the respend because the RespendLogger doesn't log equivalent clones.
=> Use respend framework for respends found in blocks

src/Makefile.am, src/init.cpp, src/utildebug.cpp, src/utildebug.h
This includes c5f008a from https://github.com/bitcoin/bitcoin/pull/9856
In addition, to be able to debug cause of OOM, I've made the OOM handler dump a backtrace.
Example output:
```
$ ./bitcoind 
Backtrace dump:
./bitcoind(+0x35cc38)[0x5654c1282c38]
./bitcoind(+0x61469)[0x5654c0f87469]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x2c)[0x7f927a36a46c]
./bitcoind(+0x6a9fc)[0x5654c0f909fc]
./bitcoind(+0x39b05)[0x5654c0f5fb05]
./bitcoind(+0x3a092)[0x5654c0f60092]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f927978f1c1]
./bitcoind(+0x38faa)[0x5654c0f5efaa]
To translate addresses to symbols, start GDB (gdb ./bitcoind)
Then call 'info symbol <address>'
Example stacktrace:
./bitcoind(+0x39ae5)[0x56140c19dae5]
Example GDB output:
(gdb) info symbol +0x39ae5
AppInit(int, char**) + …
```
=> Terminate immediately when allocation fails

src/Makefile.am, src/bitcoin-cli.cpp, src/httprpc.cpp, src/init.cpp, src/qt/rpcconsole.cpp, src/rest.cpp, src/rpc/blockchain.cpp, src/rpc/mining.cpp, src/rpc/misc.cpp, src/rpc/net.cpp, src/rpc/protocol.cpp, src/rpc/protocol.h, src/rpc/rawtransaction.cpp, src/rpc/register.h, src/rpc/server.cpp, src/rpc/server.h, src/test/rpc_tests.cpp, src/test/test_bitcoin.cpp, src/wallet/rpcdump.cpp, src/wallet/rpcwallet.cpp, src/wallet/rpcwallet.h, src/wallet/test/rpc_wallet_tests.cpp, src/wallet/test/wallet_test_fixture.cpp
https://github.com/bitcoin/bitcoin/pull/8788
Depends on #330
=> [RPC] Give RPC commands more information about the RPC request

src/rpc/server.cpp
https://github.com/bitcoin/bitcoin/pull/9042
=> [rpc] ParseHash: Fail when length is not 64

src/options.cpp, src/options.h, src/qt/test/guiutiltests.cpp, src/qt/test/uritests.cpp, src/test/blockannounce_tests.cpp, src/test/chainparams_tests.cpp, src/test/clientversion_tests.cpp, src/test/dstencode_tests.cpp, src/test/miner_tests.cpp, src/test/options_tests.cpp, src/test/rpc_tests.cpp, src/test/utilfork_tests.cpp, src/test/utilprocessmsg_tests.cpp
This removes the need to implement a custom DummyArgGetter when overriding options in unittests.
Also turned Opt into a class (instead of struct)
=> Introduce DummyArgGetter

qa/pull-tester/rpc-tests.py
-v for verbose, outputs the command called to run each test script
Useful to find the parameters needed to debug a rpc test.
```
dagurval@dev:~/bitcoinxt$ ./qa/pull-tester/rpc-tests.py -v pruning
Run: /home/dagurval/bitcoinxt/qa/rpc-tests/pruning.py --srcdir=/home/dagurval/bitcoinxt/src --portseed=0
```
=> Add verbose flag to rpc-tests

src/blockannounce.cpp, src/blockheaderprocessor.cpp, src/blockheaderprocessor.h, src/blockprocessor.cpp, src/blockprocessor.h, src/compactblockprocessor.cpp, src/main.cpp, src/process_xthinblock.cpp, src/test/blockannounce_tests.cpp, src/test/blockheaderprocessor_tests.cpp, src/test/compactblockprocessor_tests.cpp, src/test/processmessage_tests.cpp
The first commit is a bugfix where we would exceed MAX_BLOCKS_IN_TRANSIT_PER_PEER. The second commit mitigates having us misbehave nodes for sending unconnected headers. See commit description for details.
=> Improve handling of block announcements

src/chainparams.cpp, src/chainparams.h, src/init.cpp
This flag (when set to 0) makes testnet and regtest behave like mainnet by rejecting nonstandard transactions.  The flag name and behavior is awkwardly chosen to be compatible with other Satoshi clients.
Also I fixed a small issue in the description of datacarriersize.
=> add acceptnonstdtxn flag

qa/pull-tester/rpc-tests.py, qa/rpc-tests/p2p-compactblocks-limits.py, src/blockencodings.cpp, src/blockencodings.h, src/compactprefiller.h, src/compactthin.cpp, src/compacttxfinder.cpp, src/options.cpp, src/test/blockencodings_tests.cpp, src/test/compactthin_tests.cpp, src/test/thinblock_tests.cpp, src/thinblock.cpp, src/thinblock.h, src/thinblockbuilder.cpp, src/thinblockbuilder.h
This bumps the upper boundry of the index range from 2^16 to 2^32.
Also includes performance improvements for reconstructing thin blocks.
Depends in #343
=> Compact blocks updates

qa/rpc-tests/p2p-compactblocks.py
The network is not segregated by segregated witness, so no need to manually sync it.
=> [qa] Don't manually sync blocks in p2p-compactblocks

qa/rpc-tests/blockchain.py, src/chain.h, src/coins.cpp, src/coins.h, src/main.cpp, src/main.h, src/rpc/blockchain.cpp, src/test/coins_tests.cpp, src/txdb.cpp, src/txdb.h
https://github.com/bitcoin/bitcoin/pull/7756 - Add cursor to iterate over utxo set, use this in `gettxoutsetinfo`
https://github.com/bitcoin/bitcoin/pull/7815 - Break circular dependency main ↔ txdb                  
https://github.com/bitcoin/bitcoin/pull/7904 - txdb: Fix assert crash in new UTXO set cursor  
https://github.com/bitcoin/bitcoin/pull/10445 - Fix and add test for empty chain and reorg consistency for gettxoutsetinfo.
On top of #347
=> Add cursor to iterate over utxo set

src/main.cpp, src/main.h, src/script/bitcoinconsensus.cpp, src/script/interpreter.cpp, src/script/interpreter.h, src/script/sigcache.h, src/test/coins_tests.cpp, src/test/script_P2SH_tests.cpp, src/test/transaction_tests.cpp, src/txmempool.cpp
https://github.com/bitcoin/bitcoin/pull/6061 - Separate Consensus::CheckTxInputs and GetSpendHeight in CheckInputs
https://github.com/bitcoin/bitcoin/pull/7276 - Report non-mandatory script failures correctly
https://github.com/bitcoin/bitcoin/pull/7976 - Remove obsolete reference to CValidationState from UpdateCoins
https://github.com/bitcoin/bitcoin/pull/8346 - Mempool: Use Consensus::CheckTxInputs direclty over main::CheckInputs
https://github.com/bitcoin/bitcoin/pull/8524 - Precompute sighashes
https://github.com/bitcoin/bitcoin/pull/8651 - Predeclare PrecomputedTransactionData as struct
On top of #365, #358
=> Precompute sighashes

contrib/gitian-debian/postinst, contrib/gitian-debian/templates
The package in our Debian repository already has this patch applied.
fixes #383
=> Replace BCC ticker with BCH in debian package

src/hash.cpp, src/hash.h, src/main.cpp, src/test/hash_tests.cpp
Avoid VLA in hash.h - https://github.com/bitcoin/bitcoin/pull/9791
e484652fc and e484652fc from Core#10195
=> Introduce CHashVerifier + specialization of SipHash for 256 + 32 bit data

src/crypto/ripemd160.h, src/crypto/sha1.h, src/crypto/sha256.h, src/crypto/sha512.h, src/rpc/blockchain.cpp
https://github.com/bitcoin/bitcoin/pull/7848
Skipped the release-notes commit when cherry-picking.
=> Divergence between 32- and 64-bit when hashing >4GB affects `gettxoutsetinfo`

qa/rpc-tests/blockchain.py, src/coins.h, src/main.cpp, src/rest.cpp, src/rpc/blockchain.cpp, src/test/coins_tests.cpp, src/test/transaction_tests.cpp, src/undo.h
d34242430 from Core#10195, in addition to a change on BIP64 where tx version is replaced with dummy version 0.
On top of #395  and #393 
No conflicts.
=> Remove/ignore tx version in utxo and undo 

doc/build-unix.md
libcurl4-openssl-dev requires libssl 1.0, but is happy to link with
libssl 1.1 on debian systems, resulting in a segfault.
Workaround problem by using libcurl4-gnutls-dev
fixes #382
=> [doc] Replace dependency libcurl4-openssl-dev with libcurl4-gnutls-dev

src/main.cpp, src/undo.h
7d991b55d and 422634e2f from Core#10195
On top of #407 
Trivial conflict in main (function signature)
Changes in coins_tests skipped. I plan to introduce these changes after a later patch (05293f3cb removes ModifyNewCoins, that we never introduced).
The change in undo.h introduced `MAX_INPUTS_PER_BLOCK` that does not make sense for us. This constant is replaced with MAX_INPUTS_PER_TX, [as done in ABC](https://reviews.bitcoinabc.org/rABC421bf43c7b8af31cb16fa85818e45e1c0833ae25).
=> Use coin in undo

src/Makefile.bench.include, src/bench/base58.cpp, src/bench/bench.cpp, src/bench/bench.h, src/bench/ccoins_caching.cpp, src/bench/coin_selection.cpp, src/bench/crypto_hash.cpp, src/bench/mempool_eviction.cpp, src/bench/perf.cpp, src/bench/perf.h, src/bench/verify_script.cpp, src/script/bitcoinconsensus.h
https://github.com/bitcoin/bitcoin/pull/8039 - bench: Add crypto hash benchmarks
https://github.com/bitcoin/bitcoin/pull/8107 - bench: Added base58 encoding/decoding benchmarks
https://github.com/bitcoin/bitcoin/pull/8111 - Benchmark SipHash
https://github.com/bitcoin/bitcoin/pull/8115 - Avoid integer division in the benchmark inner-most loop.
https://github.com/bitcoin/bitcoin/pull/8873 - Add microbenchmarks to profile more code paths.
https://github.com/bitcoin/bitcoin/pull/9200 - bench: Fix subtle counting issue when rescaling iteration count
Most of these applied with no or trivial conflicts, except for https://github.com/bitcoin/bitcoin/pull/8873. The modifications needed were done in a separate commit.
=> Benchmark cherries

src/bench/ccoins_caching.cpp, src/bitcoin-tx.cpp, src/consensus/tx_verify.cpp, src/main.cpp, src/rpc/rawtransaction.cpp, src/test/script_P2SH_tests.cpp, src/test/transaction_tests.cpp
f68cdfe92 from Core#10195
On top of #410 and #408 
Mostly trivial merges, notable conflicts:
* tx_verify.cpp - patched to keep error() logging
* sigopcount_tests.cpp - skipped changes for a test we don't have
=> Switch from per-tx to per-txout CCoinsViewCache methods in some places

src/main.cpp, src/main.h, src/test/script_P2SH_tests.cpp, src/test/transaction_tests.cpp
On top of #411 
c87b957a3 and 8b3868c1b from Core#10195
These conflicted on almost every code line, however the conflicts were trivial.
=> Switch CScriptCheck to use Coin instead of CCoins

src/main.cpp, src/test/coins_tests.cpp
On top of #410 
This copies over coins_tests.cpp at Bitcoin Core commit
"961e4839 - Switch tests from ModifyCoins to AddCoin/SpendCoin".
Reason for updating the tests by copy is because the updates were
written for an intermediate solution "ModifyNewCoins", we never
introduced this solution, nor do we want to.
No conflicts.
=> Update coins_tests.cpp as of 961e4839

src/coins.cpp, src/coins.h, src/core_memusage.h, src/init.cpp, src/main.cpp, src/memusage.h, src/qt/transactiondesc.cpp, src/rest.cpp, src/rpc/blockchain.cpp, src/rpc/rawtransaction.cpp, src/test/coins_tests.cpp, src/txdb.cpp, src/txdb.h, src/txmempool.cpp, src/txmempool.h
508307968 from Core#10195
Notable conflicts:
* txmempool.cpp: Patching required in CCoinsViewMemPool::GetCoins
* txmempool.cpp: Changes in TrimToSize skipped
* txmempool.cpp: GetPriorty patched
* txdb.cpp: Removed function BatchWriteCoins
* test_bitcoin_fuzzy.cpp: Changes skipped, we don't have it.
* main.cpp: AcceptToMemoryPool needed patching.
* main.cpp: BIP64 code patched
* coins.cpp: skipped HaveCoinsInCache and Uncache  (we don't have them)
Had to dig out some subtle memusage fixes to get the unit tests to pass.
=> Switch CCoinsView and chainstate db from per-txid to per-txout 

src/coins.cpp, src/coins.h, src/test/coins_tests.cpp
On top of #418 
74d0f90 and 97bf377 from https://github.com/bitcoin/bitcoin/pull/6872
ce23efaa5 from Core#10195
Uncache and HaveCoinsInCache were added to avoid having to patch the tests. These methods are currently not used, but I plan to use them in the future.
=> Extend coins_tests

src/bitcoin-tx.cpp, src/coins.cpp, src/coins.h, src/consensus/tx_verify.cpp, src/init.cpp, src/main.cpp, src/policy/policy.cpp, src/qt/transactiondesc.cpp, src/rest.cpp, src/rpc/blockchain.cpp, src/rpc/rawtransaction.cpp, src/test/coins_tests.cpp, src/txdb.cpp, src/txdb.h, src/txmempool.cpp, src/txmempool.h
This completes port of https://github.com/bitcoin/bitcoin/pull/10195
For reference, other PRs including commits from 10195 are:
#392, #393, #394, #396, #397, #407, #409, #410, #411, #414, #415, #417 and #418 
This PR also contains fix https://github.com/bitcoin/bitcoin/pull/10514
Cherry pick notes:
* Skipped commit b2af357f3
* 119e552f7 tx_verify.cpp: Changes in GetTransactionSigOpCost skipped.
* 119e552f7 policy.cpp: Changes in IsWitnessStandard skipped.
* skipped commit a5e02bc7f
=> Switch chainstate db and cache to per-txout model

configure.ac, doc/build-osx.md, src/txmempool.h
Hello, I'm new here. 👋 
Wanting to get my hands dirty and help out a little. The first problem I ran into was that I couldn't build the project in my OSX environment, so I took to fixing that. This is the result.
Specifically
- OSX needs `libevent` as a dependency (probably other envs do too?) but it wasn't in the build doc so I added that.
- boost as of v 1.66+ has some differently typed function signatures, I guess. `brew` on osx installs 1.67.0 as of this writing. So I fixed the incompatibility, same as was done in core [here](https://github.com/bitcoin/bitcoin/pull/11847/files)
- similarly, qt 5.7+ (`brew` installs 5.10.1 as the latest) had compatibility issues. Core fixed that with [this change](https://github.com/bitcoin/bitcoin/pull/9169), ~~but I tried that and it didn't work for …
=> fix build on osx

src/init.cpp, src/main.cpp, src/main.h
https://github.com/bitcoin/bitcoin/pull/7821 - init: allow shutdown during 'Activating best chain...
719de56 from https://github.com/bitcoin/bitcoin/pull/7942
The other commit (efb54ba) is not needed because nodestate has its own lock. nPreferredDownload was unprotected though, so I added a commit to make it atomic.
https://github.com/bitcoin/bitcoin/pull/8063 - Acquire lock to check for genesis block
https://github.com/bitcoin/bitcoin/pull/10290 - Add -stopatheight for benchmarking
https://github.com/bitcoin/bitcoin/pull/10305 - Fix potential NPD introduced in b297426c
https://github.com/bitcoin/bitcoin/pull/10569 - Fix stopatheight
=> Add -stopatheight for benchmarking + bugfixes

qa/rpc-tests/abc-p2p-fullblocktest.py, qa/rpc-tests/mempool_reorg.py, qa/rpc-tests/pruning.py
Once the fork deployed, these tests were sensitive to the mempool being cleared as the fork was "rolled back" by invalidations.
=> [Tests] Correct tests to pre-thirdfork env

doc/release-notes.md, qa/rpc-tests/rest.py, src/coins.cpp, src/coins.h, src/consensus/tx_verify.cpp, src/main.cpp, src/rest.cpp, src/test/coins_tests.cpp, src/txmempool.cpp, src/txmempool.h
82e8baa from https://github.com/bitcoin/bitcoin/pull/9512
https://github.com/bitcoin/bitcoin/pull/8638 - rest.cpp: change HTTP_INTERNAL_SERVER_ERROR to HTTP_BAD_REQUEST
b5fb339 from https://github.com/bitcoin/bitcoin/pull/10898
https://github.com/bitcoin/bitcoin/pull/12717 - [REST] Handle UTXO retrieval when ignoring the mempool
on top of #429
=> [REST] Handle UTXO retrieval when ignoring the mempool

src/util.cpp
Fixes #241
The code was checking for the existence of the `datadir` *before* reading and processing the config file. This means that when the datadir was only specified in the config file, we ended up checking whether the default dir existed, which it does, and then reading in a nonexistent datadir after that, causing later code (which assumes this check has already been performed and passed) to have erratic behavior.
~~So the fix is just to move the "read config" code up higher so it happens first. I think in general reading the config file should be as high as possible in this function, or maybe even up higher in the call tree? Not sure how the GUI mode interacts with the conf file yet though.~~
Fixed by checking that the datadir exists inside the `ReadConfigFile` function, just before …
=> read config file before checking for existence of datadir

src/bitcoind.cpp, src/init.cpp, src/init.h, src/qt/bitcoin.cpp
https://github.com/bitcoin/bitcoin/pull/12266
Resolves shutdown crash during startup caused by scheduler thread not being interrupted and joined before destruction in the case where initialization did not complete.
=> Move scheduler/threadGroup into common-init instead of per-app

src/httpserver.cpp
Thread startup (StartHTTPServer) is separate  from
initalization (InitHTTPServer), so we need to check whether the thread
was started before stopping it.
Fixes #381
=> Ensure http server thread is only stopped if it was started.

qa/pull-tester/rpc-tests.py, qa/rpc-tests/dbcrash.py, qa/rpc-tests/test_framework/authproxy.py, qa/rpc-tests/test_framework/test_framework.py, qa/rpc-tests/test_framework/util.py, src/blocksender.cpp, src/chain.cpp, src/chain.h, src/coins.cpp, src/coins.h, src/inflightindex.h, src/init.cpp, src/main.cpp, src/main.h, src/nodestate.h, src/random.cpp, src/random.h, src/rest.cpp, src/rpc/blockchain.cpp, src/rpc/rawtransaction.cpp, src/test/test_bitcoin.cpp, src/test/thinblockutil.h, src/txdb.cpp, src/txdb.h, src/ui_interface.h, src/utilprocessmsg.h, src/wallet/wallet.cpp
* 012fc91 from https://github.com/bitcoin/bitcoin/pull/7112
* this one is modified a bit
* https://github.com/bitcoin/bitcoin/pull/8392 - Fix several node initialization issues
* skipped aa59f2e, we already have it
* https://github.com/bitcoin/bitcoin/pull/10148 - Use non-atomic flushing with block replay
* skipped 0580ee0, we did not account for DB peak usage
* https://github.com/bitcoin/bitcoin/pull/10704 - [tests] nits in dbcrash.py
There are also multiple commits by me for better compatibility with cherry-picked changes.
=> Use non-atomic flushing with block replay

contrib/linearize/README.md, contrib/linearize/example-linearize.cfg, contrib/linearize/linearize-data.py, contrib/linearize/linearize-hashes.py
https://github.com/bitcoin/bitcoin/pull/6372 Update Linearize tool to support Windows paths
https://github.com/bitcoin/bitcoin/pull/9373 Support hash byte reversal, support python3
https://github.com/bitcoin/bitcoin/pull/9580 Fix various minor linearization script issues
https://github.com/bitcoin/bitcoin/pull/10104 Adds the a datadir option to the linearize configuration file
Only one trivial conflict.  Bypassed changes from broad refactorings.
=> Cherry-pick updates to contrib/linearize

qa/pull-tester/rpc-tests.py, qa/rpc-tests/bip64.py, qa/rpc-tests/test_framework/bip64.py, qa/rpc-tests/test_framework/mininode.py, src/Makefile.am, src/bip64_getutxo.cpp, src/bip64_getutxo.h, src/main.cpp, src/rest.cpp, src/txmempool.cpp
This introduces the class `bip64::UTXORetriever` to encapsulate and remove duplicate logic between the network message `getutxos` and the rest call `get_utxos`.
In addition a qa test for BIP64 is added.
=> BIP64 cleanup

src/init.cpp, src/util.cpp, src/util.h
This bumps number of scriptcheck threads to # virtual cores, without re-introducing the issue that using physical core count fixed (see https://github.com/bitcoin/bitcoin/pull/6361).
This should give nice speedup to #442, which reuses the `-par` parameter.
No merge conflicts.
https://github.com/bitcoin/bitcoin/pull/10271 - Use std::thread::hardware_concurrency, instead of Boost, to determine available cores
https://github.com/bitcoin/bitcoin/pull/12618 - Set SCHED_BATCH priority on the loadblk thread.
https://github.com/bitcoin/bitcoin/pull/12923 - util: Pass pthread_self() to pthread_setschedparam instead of 0
=> Default to virtual cores and set appropriate thread scheduler

src/clientversion.cpp, src/clientversion.h, src/init.cpp, src/main.cpp, src/net.cpp, src/options.cpp, src/options.h, src/respend/respenddetector.cpp, src/test/clientversion_tests.cpp
This removes stealth mode and replaces it with the option to set a custom user agent.
If we want to enable full stealth mode again, we can implement the options to disable specific features to more closely mimic a client (for example `-useragent="/BUCash:1.3.0.1/" -disablecompactblocks -disablebip64` etc.).
Closes #443
=> Replace stealth-mode with custom user agent

qa/rpc-tests/test_framework/authproxy.py, src/httpserver.cpp, src/init.cpp
Fixes #451 
* Increase RPC timeout
* https://github.com/bitcoin/bitcoin/pull/11831 - Always return true if AppInitMain got to the end
* https://github.com/bitcoin/bitcoin/pull/11593 - rpc: work-around an upstream libevent bug
* https://github.com/bitcoin/bitcoin/pull/12366 - http: Join worker threads before deleting work queue
=> Fix dbcrash failures

src/Makefile.am
Fixes linker error on OSX.
The file utxocommit.cpp uses functionality that is not part of libbitcoinconsensus, including "compressor.cpp"
=> Move utxocommit from consensus to common

contrib/README.md, contrib/gitian-build.sh
https://github.com/bitcoin/bitcoin/pull/8566 - Easy to use gitian building script
https://github.com/bitcoin/bitcoin/pull/11391 - Remove lxcbr0 lines from gitian-build.sh
f6b3382 (squashed into next commit), b9e79ab and 564a172 from https://github.com/bitcoin/bitcoin/pull/10773/
https://github.com/bitcoin/bitcoin/pull/12394 - gitian-builder.sh: fix --setup doc, since lxc is default
https://github.com/bitcoin/bitcoin/pull/12527 - gitian-build.sh: fix signProg being recognized as two parameters
https://github.com/bitcoin/bitcoin/pull/13320 - Ensure gitian-build.sh uses bash
Tested by building Windows and Linux versions for 0.11I and the sha256sums match.
Documentation for using this is located here: https://github.com/bitcoin-core/docs/blob/master/gitian-building.md
=> Easy to use gitian building script

qa/rpc-tests/wallet.py, src/Makefile.am, src/Makefile.test.include, src/chainparams.cpp, src/clientversion.cpp, src/clientversion.h, src/consensus/merkle.cpp, src/consensus/merkle.h, src/core_memusage.h, src/init.cpp, src/main.cpp, src/miner.cpp, src/primitives/block.cpp, src/primitives/block.h, src/test/clientversion_tests.cpp, src/test/main_tests.cpp, src/test/merkle_tests.cpp, src/test/miner_tests.cpp, src/test/pmt_tests.cpp, src/thinblockbuilder.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/walletdb.cpp
On top of #445 
https://github.com/bitcoin/bitcoin/pull/6550 - Do not store Merkle branches in the wallet.
* skipped commit 3b33ec8, not confident that this is a good way to cache validation
https://github.com/bitcoin/bitcoin/pull/6508 - Switch to a constant-space Merkle root/branch algorithm.
https://github.com/bitcoin/bitcoin/pull/7757 - [qa] wallet: Wait for reindex to catch up
=> Switch to a constant-space Merkle root/branch algorithm.

qa/rpc-tests/bip68-sequence.py, src/bench/mempool_eviction.cpp, src/main.cpp, src/miner.cpp, src/policy/fees.cpp, src/policy/fees.h, src/qt/coincontroldialog.cpp, src/rpc/blockchain.cpp, src/rpc/client.cpp, src/rpc/mining.cpp, src/test/mempool_tests.cpp, src/test/miner_tests.cpp, src/test/policyestimator_tests.cpp, src/test/test_bitcoin.cpp, src/test/test_bitcoin.h, src/txmempool.cpp, src/txmempool.h, src/wallet/wallet.cpp
Estimate priority and code using it is dead code. We don't support transaction priority when generating block template anymore and there are as far as I know also no miners running node software that supports it on the network.
This includes https://github.com/bitcoin/bitcoin/pull/7730 (Remove priority estimation). Some patching required because we never added the "smart priority estimate" features.
Miner version was bumped because the estimate database file needed new versioning.
=> Remove estimate priority

src/Makefile.am, src/coins.cpp, src/coins.h, src/main.cpp, src/policy/txpriority.cpp, src/policy/txpriority.h, src/primitives/transaction.cpp, src/primitives/transaction.h, src/qt/coincontroldialog.cpp, src/txmempool.cpp, src/txmempool.h, src/wallet/wallet.cpp
Transaction priority is rules for which low fee transactions we're willing to include in the blocks we mine. It's policy.
On top of #457
=> Move transaction priority functions into policy

src/main.cpp
Timestamp that's used in debug output was read after free. Detected by valgrind.
=> Fix read of timestamp after free

src/bloom.h, src/main.cpp, src/net.cpp, src/net.h, src/respend/respendrelayer.cpp, src/respend/test/respendrelayer_tests.cpp, src/test/net_tests.cpp
Skip sending respends to peers without an effective bloom filter.  SPV clients will need to opt in to respend relay since they will not see conflicting transactions that don't pay them.
Picked from https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/1240 which implemented first.
=> Do not relay double spends to SPV clients

qa/pull-tester/rpc-tests.py, qa/rpc-tests/p2p-leaktests.py, qa/rpc-tests/p2p-timeouts.py, qa/rpc-tests/test_framework/mininode.py, src/main.cpp, src/net.cpp, src/test/p2p_protocol_tests.cpp, src/utilprocessmsg.cpp, src/utilprocessmsg.h
* fd13eca from https://github.com/bitcoin/bitcoin/pull/9674
* https://github.com/bitcoin/bitcoin/pull/9715 - Disconnect peers which we do not receive VERACKs from within 60 sec
* https://github.com/bitcoin/bitcoin/pull/9720 - net: fix banning and disallow sending messages before receiving verack
* c45b9f - I already wrote the same function as SendRejectsAndCheckIfBanned. Moved it to utilprocessmsg instead of moving it up in main.
* skipped 5b5e4f8 and 8650bbb, we already got them in 9715
=> Disallow messages before receiving VERACK

contrib/debian/manpages/bitcoin-qt.1, qa/rpc-tests/abc-p2p-fullblocktest.py, qa/rpc-tests/bip68-sequence.py, qa/rpc-tests/mempool-accept-txn.py, qa/rpc-tests/mempool_packages.py, qa/rpc-tests/mempool_reorg.py, qa/rpc-tests/mempool_resurrect_test.py, qa/rpc-tests/mempool_spendcoinbase.py, qa/rpc-tests/merkle_blocks.py, qa/rpc-tests/smartfees.py, qa/rpc-tests/spv.py, qa/rpc-tests/test_framework/util.py, qa/rpc-tests/wallet.py, src/Makefile.am, src/Makefile.test.include, src/init.cpp, src/main.cpp, src/mempoolaccepter.cpp, src/mempoolaccepter.h, src/miner.cpp, src/options.cpp, src/options.h, src/policy/policy.h, src/test/mempoolaccepter_tests.cpp
This split out transaction fee/priority evaluation out of `AcceptToMemoryPool` and into a class `FeeEvaluator`. This class is given unit test coverage, and the tests clearly define transaction acceptance policy.
The somewhat broken `-relaypriority` parameter is replaced with a more descriptive `-allowfreetx` parameter.
QA tests that broke due to fee policy change are fixed.
On top of #459
=> Refactor tx fee/priority evaluation out of AcceptToMemoryPool

src/primitives/transaction.h, src/test/uint256_tests.cpp, src/uint256.h
* https://github.com/bitcoin/bitcoin/pull/7712 - Improve COutPoint less operator
* https://reviews.bitcoinabc.org/D1526 - Add support for both way comparison for uint256/uint160
* Random code formatting changes removed
* https://reviews.bitcoinabc.org/D1527 - Modify uint256's comparison to use proper endianess
* Changed to const reference for `a` and `b` in `base_blob::Compare`
As far as I can tell, nothing depended on the existing behavior of `base_blob::Compare`, only that there was an order. This is a prerequisite for CTOR.
=> Add operator> to base_blob and use proper endianess

src/bitcoin-tx.cpp, src/core_io.h, src/core_read.cpp, src/rpc/rawtransaction.cpp, src/test/blockencodings_tests.cpp, src/test/core_io_tests.cpp, src/test/testutil.cpp, src/test/testutil.h, src/wallet/rpcwallet.cpp
This improves the output from the RPC interface.
```
decoderawtransaction 0100000001db4f85b6e2b9f6378fd9f52d80e17c63153D61e1cbc4d46632bf2aba3190d5b000000000000000000001000000000000000001510000000000
TX decode failed: Excess data in hex string. After parsing transaction, 1 bytes remained. (code -22)
```
=> Throw detailed error from DecodeHexTx

src/test/maxblocksize_tests.cpp, src/test/testutil.cpp, src/test/testutil.h
Make code for chaining a dummy index reusable with new function `BuildDummyBlockIndex`.
I plan to use this with #477
=> [test] Add helper function BuildDummyBlockIndex

src/main.cpp
This makes RollforwardBlock support any transaction order.
It's a prerequisite for supporting AOR (Any-order-rule) and CTOR.
https://reviews.bitcoinabc.org/D1479
Changes from original commit:
* Removed optimization in `UpdateCoins(tx, inputs, nHeight)` - that optimization removes the need to copy txundo, but duplicates code.
* Did not add header declaration for SpendCoins, but made it static instead.
=> [fork] Remove ordering requirement in RollforwardBlock

qa/rpc-tests/invalidblockrequest.py
9b4a36e from https://github.com/bitcoin/bitcoin/pull/14247
We don't have the bug, but let's add the test to not regress.
=> [qa] Test for duplicate inputs within a transaction

src/chainparams.cpp
Until we can test a fix for issue #494, set MinBlockFileBlocks to 64.  This needs to be revisited when the max block size is increased beyond 32MB.
=> Keep block files under 2GB thanks to windows fseek

src/Makefile.am, src/Makefile.test.include, src/bench/verify_script.cpp, src/bitcoin-tx.cpp, src/core_write.cpp, src/rpc/rawtransaction.cpp, src/script/interpreter.cpp, src/script/interpreter.h, src/script/sighashtype.cpp, src/script/sighashtype.h, src/script/sign.cpp, src/script/sign.h, src/test/DoS_tests.cpp, src/test/multisig_tests.cpp, src/test/script_P2SH_tests.cpp, src/test/script_tests.cpp, src/test/sighash_tests.cpp, src/test/sighashtype_tests.cpp, src/test/transaction_tests.cpp, src/wallet/wallet.cpp
Gives signature hash types a typename, thus adding type safety.
This is a less intrusive alternative to the `SigHashType` enum wrapper class introduced by ABC. Also this is an alternative to BU's approach to keep both the enum and introduce ABC's class, as done in their DSV PR https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/1390
This change makes it easier to port signature encoding tests and DSV.
=> Convert signature hash type to enum class

src/Makefile.am, src/core_write.cpp, src/pubkey.cpp, src/pubkey.h, src/script/interpreter.cpp, src/script/interpreter.h, src/script/script_error.h, src/script/script_flags.h, src/script/sigencoding.cpp, src/script/sigencoding.h, src/test/sigencoding_tests.cpp
On top of #500 
* Use sliced to remove the sighash byte from a signature to check for low S - https://reviews.bitcoinabc.org/D1572
* Refactor IsValidSignatureEncoding - https://reviews.bitcoinabc.org/D1576
* Ignore sighash when checking for DER encoding. - https://reviews.bitcoinabc.org/D1577
* Refactor signature encoding checks to separates checks of the SigHashType and other checks - https://reviews.bitcoinabc.org/D1578
* Add CheckDataSignatureEncoding to check signature with a sighashtype. - https://reviews.bitcoinabc.org/D1579
* Make sigencoding_tests significantly faster by not checking the full sigashtype/flags combinatorial - https://reviews.bitcoinabc.org/D1580
Also includes a MOVEONLY commit for signature encoding stuff to ease cherry picking.
=> Refactors of signature encoding check

src/main.cpp, src/main.h, src/net.cpp, src/net.h
Eliminate artificial delays from transaction relay.
Relay delays were added by Bitcoin Core to improve certain kinds of privacy, but the delays were never quantitatively justified.  At the recent BCH instant transactions development conference, there was universal agreement that Bitcoin Cash cannot afford to sacrifice any tx relay speed as it strives for instantly reliable transactions.  Users have several independent avenues for protecting their privacy.
Bitcoin Unlimited has already deployed essentially the policy that results from this change.
The trickle code did not have test coverage, so no test modifications were needed. However, in my trials, the qa test suite as a whole runs over 10 minutes faster with this change.
=> Eliminate artificial transaction relay delays

src/wallet/wallet.cpp
This check as is allowed for transacting before BCH forked from BTC. But now that the fork has happened, we want to always want to sign with FORKID.
=> [wallet] Always enable replay protection for BCH

qa/pull-tester/rpc-tests.py, qa/rpc-tests/abc-transaction-ordering.py, src/checkqueue.h, src/main.cpp, src/main.h, src/script/interpreter.h, src/test/coins_tests.cpp, src/test/script_P2SH_tests.cpp, src/test/transaction_tests.cpp
* Make a copy of PrecomputedTransactionData in the CScriptCheck - https://reviews.bitcoinabc.org/D297
* Did not move the header declaration of PrecomputedTransactionData
* Did not add a copy constructor (we'll rely on implicitly-declared)
* Process transactions in two loops in ConnectBlock instead of one - https://reviews.bitcoinabc.org/D1484
* Needed some patching. ABC has refactored the sigop counting.
* Remove topological ordering constraint from block starting Nov, 15 2018 - https://reviews.bitcoinabc.org/D1487
* Test needed some patching due to test framework differences
* Update ApplyBlockUndo to be able to undo out of order blocks - https://reviews.bitcoinabc.org/D1528
* Compiler started to complain about returning `int`, so I converted DisconnectResult into an `enum class`. The …
=> [fork] Introduce Any-Order-Rule

src/init.cpp, src/main.cpp, src/qt/clientmodel.cpp, src/qt/clientmodel.h, src/qt/forms/rpcconsole.ui, src/qt/rpcconsole.cpp, src/qt/rpcconsole.h, src/rpc/blockchain.cpp, src/txmempool.cpp, src/txmempool.h
Maintain mempool TPS rate and return in getmempoolinfo.  This the current mempool tx admission rate over a 60-second window.
Also add other getmempoolinfo and debug window data.
https://github.com/bitcoin/bitcoin/pull/6529 [Qt] show client user agent in debug window
https://github.com/bitcoin/bitcoin/pull/6877 rpc: Add maxmempool to getmempoolinfo
https://github.com/bitcoin/bitcoin/pull/6979 [Qt] simple mempool info in debug window
https://github.com/bitcoin/bitcoin/pull/7069 [trivial] Fix -maxmempool InitError
https://github.com/bitcoin/bitcoin/pull/7118 Describe maxmempool in the getmempoolinfo RPC help
https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/35 Adding Transactions Per Second output to the debug window
https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/50 Fix …
=> [rpc] Return tx-per-second in getmempoolinfo response
